apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-qa
  namespace: argocd
spec:
  project: project-apps
  source:
    repoURL: 'https://github.com/AnilNarayanaswamym/aks-argocd.git'
    targetRevision: HEAD
    path: my-app/charts/sample-app   # or path to your Helm chart
    helm:
      valueFiles:
        - values-qa.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true